// Ed25519 public key (raw 32-byte, hex) — generated by support-tools/generate-keys.js
export const EMBEDDED_PUBLIC_KEY_HEX = '605bdf277723578520bf50ad0c644217dde846815be9a4730119618d2a25f495';

// Shared secret for cancel key verification — known to Support tool and embedded here
// Not a cryptographic secret for data protection; used only to verify revoke authenticity
export const CANCEL_SECRET = 'c7b8781afdc8033045fd93c68f05d539c50c7c2cf354424d2082abe702f00c56';

// Keychain / Registry service name
export const LICENSE_SERVICE = 'invoice-builder';
export const LICENSE_SALT_KEY = 'license-salt';
export const LICENSE_ACTIVATION_KEY = 'license-activation';
